services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    restart: always
    depends_on:
      - vmware_exporter
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    user: "104"
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
    - prometheus
    restart: always
  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    ports:
      - '9001:9001'
    env_file:
      - .env
    restart: always
  vmware_exporter:
    image: pryorda/vmware_exporter:latest
    restart: always
    hostname: vmware_exporter
    container_name: vmware_exporter
    environment:
      - VSPHERE_IGNORE_SSL=True
      - VSPHERE_USER=${VSPHERE_USER}
      - VSPHERE_PASSWORD=${VSPHERE_PASSWORD}
      - VSPHERE_HOST=${VSPHERE_HOST}
      - VSPHERE_SPECS_SIZE=2000
    ports:
      - 9272:9272
    env_file:
      - .env
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    restart: always